import Head from "next/head";
import { api } from "~/utils/api";
import Navbar from "~/components/navbars/Navbar";
import BookReviewEditor from "~/components/bookreviews/BookReviewEditor";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <BookReviewEditor
          onSave={(data) => {
            console.log(`Saving ${data.title}`);
          }}
          onDelete={(data) => {
            console.log(`Deleting ${data.title}`);
          }}
          onPublish={(data) => {
            console.log(`Publishing ${data.title}`);
          }}
        />
      </main>
    </>
  );
}
